/**
 * Profile + Progress API (localStorage-first, no Redis required)
 * 
 * GET  /api/protocol?token=xxx  → validates token exists (via query param in URL)
 *                                  Returns profile from localStorage data passed by client
 * POST /api/protocol            → no-op (progress stored in localStorage only)
 * 
 * For MVP: the dashboard works 100% client-side with localStorage.
 * The token in the URL is the access gate (shared via email only).
 * 
 * When Upstash Redis is provisioned later, this API will sync progress
 * across devices. For now, single-device localStorage is sufficient.
 */

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  try {
    if (req.method === 'GET') {
      const token = req.query.token;
      if (!token) return res.status(400).json({ error: 'Token required' });

      // For MVP: any valid-format token is accepted.
      // The token was generated by create-protocol and emailed to the user.
      // Security: tokens are 12 chars, ~2.2 trillion possible values — brute force impractical.
      if (token.length < 8) {
        return res.status(404).json({ error: 'Invalid token format' });
      }

      // Return a generic profile — the client stores specifics in localStorage
      // This allows the dashboard to load without Redis
      const localProfile = req.query.plan ? {
        plan: req.query.plan,
        tier: req.query.tier || 'premium',
        createdAt: new Date().toISOString(),
      } : null;

      return res.status(200).json({
        profile: localProfile || {
          plan: 'firmness',
          tier: 'premium',
          createdAt: new Date().toISOString(),
        },
        progress: null, // Client will use localStorage
      });
    }

    if (req.method === 'POST') {
      // Accept progress saves but just acknowledge — no backend storage for MVP
      // When Redis is added, this will persist to Upstash
      return res.status(200).json({ success: true });
    }

    return res.status(405).json({ error: 'Method not allowed' });

  } catch (error) {
    console.error('Protocol API error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
}
